[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5"
csv = "1.3"
plotters = "0.3"
gif = "0.12"
image = { version = "0.25", default-features = false, features = ["bmp", "png"] }
imageproc = "0.25"

bitvec = "1.0.1"
nom = "7.1.3"
eyre = "0.6.12"
